name: tests

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
  
            - name: install gtest library
              run: sudo apt-get install libgtest-dev          
            - name: create build files
              run: mkdir build && cd build && cmake ..
            - name: make
              run: cd build && make
    tests:
        runs-on: ubuntu-latest
        needs: build
        steps:
            - uses: actions/checkout@v1
            
            - name: install gtest library
              run: sudo apt-get install libgtest-dev
            - name: create build files
              run: mkdir build && cd build && cmake ..
            - name: make
              run: cd build && make
            - name: run tests
              run: ./build/tests/cipher_tests
